{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default 1 }}
  {{- end }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
    spec:
      {{- if .Values.hostAliases }}
      hostAliases:
        {{ toYaml .Values.hostAliases | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: { }
        {{- with .Values.extraVolumes }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
      automountServiceAccountToken: false
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.registry.host }}/{{ .Values.image.imageName }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              # Tmp folder used by spring to write data. We need to mount this because of "readOnlyRootFilesystem" (see above)
              mountPath: /tmp/
            {{- with .Values.extraVolumeMounts }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          ports:
            - name: {{ .Values.service.serverPort.name }}
              containerPort: {{ .Values.service.serverPort.target }}
              protocol: TCP
          {{- if .Values.actuatorEnabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.serverPort.target }}
            initialDelaySeconds: {{ .Values.health.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.health.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.health.liveness.periodSeconds }}
            failureThreshold: {{ .Values.health.liveness.failureThreshold }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.serverPort.target }}
            initialDelaySeconds: {{ .Values.health.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.health.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.health.readiness.periodSeconds }}
            failureThreshold: {{ .Values.health.readiness.failureThreshold }}
          {{- end }}
          env:
            {{- range $k, $v := .Values.container.env.vars }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
            {{- range $k, $v := .Values.container.env.additionalVars }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          envFrom:
            {{- range .Values.container.env.configMaps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.container.env.secrets }}
            - secretRef:
                name: {{ . }}
             {{- end }}
    {{- with .Values.hostAliases }}
      hostAliases:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.imagePullSecret.enabled | default false }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
{{- end }}